apiVersion: apps/v1
kind: Deployment
metadata:
  name:  tomcat-deployment-01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat-deployment-01
  template:
    metadata:
      labels:
        app: tomcat-deployment-01
    spec:
      containers:
        - name: tomcat-pod
          image: melca/default-tomcat:8.5
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service-01
spec:
  selector:
    app: tomcat-deployment-01
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32227