apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
### default settings
#  ports:
#  - port: 3306
#  selector:
#    app: mysql
#  clusterIP: None

### custom settings
  type: NodePort
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      nodePort: 30000 # external port
      targetPort: 3306
